from __future__ import annotations

import json

import pytest

from sqlmend_retrieval.hashing import (
    audit_protected_paths,
    snapshot_release_source,
)
from sqlmend_retrieval.paths import ProjectPaths


def _paths(tmp_path):
    root = tmp_path / "repo"
    (root / "construction").mkdir(parents=True)
    (root / "annotation" / "codex").mkdir(parents=True)
    (root / "construction" / "input.bin").write_bytes(b"construction")
    (root / "annotation" / "codex" / "input.bin").write_bytes(b"annotation")
    return ProjectPaths(root)


def test_before_audit_is_anchored_and_cannot_rebaseline_changed_bytes(tmp_path):
    paths = _paths(tmp_path)
    first = audit_protected_paths(paths, "before")
    second = audit_protected_paths(paths, "before")
    assert second == first

    original_report = paths.protected_report.read_bytes()
    (paths.annotation / "input.bin").write_bytes(b"changed")
    with pytest.raises(RuntimeError, match="Refusing to overwrite"):
        audit_protected_paths(paths, "before")
    assert paths.protected_report.read_bytes() == original_report

    after = audit_protected_paths(paths, "after")
    assert after["protected_paths_unchanged"] is False
    assert after["differences"]["changed"] == ["annotation/codex/input.bin"]


def test_release_source_snapshot_ignores_generated_caches(tmp_path):
    paths = _paths(tmp_path)
    source = paths.retrieval / "src" / "package" / "module.py"
    source.parent.mkdir(parents=True)
    source.write_text("VALUE = 1\n", encoding="utf-8")
    (paths.retrieval / "README.md").write_text("readme\n", encoding="utf-8")
    before = snapshot_release_source(paths)

    pycache = source.parent / "__pycache__"
    pycache.mkdir()
    (pycache / "module.cpython-312.pyc").write_bytes(b"generated bytecode")
    pytest_cache = paths.retrieval / "tests" / ".pytest_cache"
    pytest_cache.mkdir(parents=True)
    (pytest_cache / "state").write_text(json.dumps({"changed": True}), encoding="utf-8")

    assert snapshot_release_source(paths) == before
